# Generated by Django 4.0 on 2022-01-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('pub_date', models.DateField()),
                ('prod_price', models.IntegerField()),
            ],
        ),
    ]
