# Generated by Django 4.0 on 2022-01-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funnytimes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='funnytimes/images'),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_cat',
            field=models.CharField(default='', max_length=50),
        ),
    ]
