# Generated by Django 4.0 on 2022-02-01 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funnytimes', '0002_product_category_product_image_product_sub_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=70)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.TextField(max_length=15)),
                ('desc', models.TextField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=5000),
        ),
    ]
