# Generated by Django 4.0 on 2022-02-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funnytimes', '0003_contact_alter_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('cust_name', models.TextField(max_length=70)),
                ('cust_email', models.EmailField(max_length=100)),
                ('cust_phone', models.TextField(max_length=15)),
                ('cust_address', models.TextField(max_length=500)),
                ('cust_city', models.TextField(max_length=15)),
                ('cust_zip', models.TextField(max_length=15)),
                ('cust_state', models.TextField(max_length=15)),
                ('cust_country', models.TextField(max_length=15)),
                ('order_items', models.TextField(max_length=500)),
            ],
        ),
    ]
