# Generated by Django 4.0 on 2022-02-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funnytimes', '0004_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track_order',
            fields=[
                ('track_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.CharField(max_length=75)),
                ('track_desc', models.CharField(max_length=500)),
                ('track_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
