# Generated by Django 4.0 on 2022-03-01 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funnytimes', '0007_alter_order_options_order_paid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='razon_payment_id',
            new_name='razor_payment_id',
        ),
    ]
