# Generated by Django 4.0 on 2022-03-04 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funnytimes', '0008_rename_razon_payment_id_order_razor_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='razor_order_id',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
