# Generated by Django 4.0 on 2022-03-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funnytimes', '0009_order_razor_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_price',
            field=models.TextField(default=0, max_length=50),
        ),
    ]
